### ISSUE TITLE
Does Nim requirement have to be >=1.2?

### ISSUE THREAD

**Issue by narimiran** [yglukhov/wasmrt#2]
Is it possible for this package to use Nim >=1.0, or is `requires "nim >= 1.2"` necessary?

I'm asking because this package is used by your https://github.com/yglukhov/jsbind, which is in turn used by @brentp's https://github.com/brentp/nim-plotly, which is used by @bluenote's https://github.com/bluenote10/NimData — making those packages now fail with Nim 1.0.x CIs.

**Comment by yglukhov** [comment]
Oops, sorry
